[general]
import = ["/home/jj/.nix-profile/monokai_charcoal.yaml"]

[font]
bold = { family = "Fira Code Nerd Font Mono" }
bold_italic = { family = "Fira Code Nerd Font Mono" }
italic = { family =  "Fira Code Nerd Font Mono" }
normal = { family = "Fira Code Nerd Font Mono" }
size = 10

[window]
decorations = "Full"
decorations_theme_variant = "Dark"
opacity = 0.8
padding = { x = 10, y = 10 }

[scrolling]
history = 1000
multiplier = 3
