keys:
  users:
    - &jj_arch age1vvq5cg8x8x807v803608ehnu09aquvuzx9kcsmws02ly7cj5tg5smfkfyw
    - &jj age1spnpykk9qxf28qltfyevq2scvjhe3jtcr98pneps88uul37fgs0sjtnyk2
  systems:
    - &nixos age1qlvrrh5rg9ys79z9tq0fjgm3r9km8hzvt65mj8qa27ezzqaeqpxq5qd0f6
    - &snowy age1ql28mv4vcsux4hv3gmg593srznzk4y8lvcj8xac23eaqvaz47dmqqhcf38
creation_rules:
  - path_regex: ^.*x270/secrets/secrets\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *jj
      - *nixos
  - path_regex: ^.*snowy/secrets/secrets.yaml$
    key_groups:
    - age:
      - *jj_arch
      - *snowy
  - path_regex: ^.*arch/secrets.yaml$
    key_groups:
    - age:
      - *jj_arch